import json
from pathlib import Path

import pytest

from course_mcp_server.licensing import (
    License,
    check_export_quota,
    exports_this_month,
    hash_key,
    issue_license,
    record_export,
    resolve_license,
)
from course_mcp_server.security import SecurityError


@pytest.fixture()
def license_store(tmp_path, monkeypatch):
    store = tmp_path / "licenses.json"
    monkeypatch.setenv("LICENSE_STORE_PATH", str(store))
    monkeypatch.setenv("MCP_API_TOKEN", "admin-bootstrap-token")
    monkeypatch.delenv("MCP_API_TOKEN_FILE", raising=False)
    return store


def test_bootstrap_token_resolves_to_admin(license_store):
    license_ = resolve_license("admin-bootstrap-token")
    assert license_.tier == "admin"
    assert license_.monthly_export_quota is None
    assert license_.white_label


def test_issued_key_resolves_with_tier_and_quota(license_store):
    issue_license("cmk_customer_key", tenant="acme", tier="pro")
    license_ = resolve_license("cmk_customer_key")
    assert license_.tenant == "acme"
    assert license_.tier == "pro"
    assert license_.monthly_export_quota == 50
    assert not license_.white_label
    stored = json.loads(Path(license_store).read_text())
    assert stored["licenses"][0]["key_hash"] == hash_key("cmk_customer_key")
    assert "cmk_customer_key" not in Path(license_store).read_text()


def test_unknown_and_disabled_keys_are_rejected(license_store):
    with pytest.raises(SecurityError):
        resolve_license("cmk_never_issued")
    issue_license("cmk_disabled", tenant="gone", tier="free")
    store = json.loads(Path(license_store).read_text())
    store["licenses"][0]["disabled"] = True
    Path(license_store).write_text(json.dumps(store))
    with pytest.raises(SecurityError):
        resolve_license("cmk_disabled")


def test_export_quota_metering(license_store):
    issue_license("cmk_free", tenant="tiny", tier="free")
    license_ = resolve_license("cmk_free")
    assert check_export_quota(license_)["allowed"] is True
    record_export(license_)
    record_export(license_)
    assert exports_this_month("tiny") == 2
    quota = check_export_quota(license_)
    assert quota["allowed"] is False
    assert quota["used"] == 2
    assert quota["quota"] == 2


def test_white_label_tier_is_unlimited(license_store):
    issue_license("cmk_wl", tenant="brandco", tier="white_label")
    license_ = resolve_license("cmk_wl")
    assert license_.white_label
    for _ in range(5):
        record_export(license_)
    assert check_export_quota(license_)["allowed"] is True


def test_quota_exceeded_blocks_export_tool(tmp_path, monkeypatch, license_store):
    monkeypatch.setenv("COURSE_PROJECT_STORE_PATH", str(tmp_path / "projects.json"))
    monkeypatch.setenv("OUTPUT_DIR", str(tmp_path / "output"))
    from course_mcp_server.security import RequestContext
    from course_mcp_server.tools import build_export_package, create_course_project

    context = RequestContext(tenant_id="tiny", user_id="u", request_id="r", tier="free")
    project = create_course_project(
        {"course_title": "Quota Course", "audience": "testers", "language": "English"}, context
    )
    license_ = License(tenant="tiny", tier="free", monthly_export_quota=2)
    record_export(license_)
    record_export(license_)

    result = build_export_package({"project_id": project["data"]["project_id"], "export_format": "scorm"}, context)
    assert result["ok"] is False
    assert result["error"] == "quota_exceeded"


def test_white_label_branding_replaces_footer(tmp_path):
    from zipfile import ZipFile

    from course_mcp_server.exporters.scorm import build_scorm_package
    from course_mcp_server.schemas import ScormPackageRequest

    result = build_scorm_package(
        ScormPackageRequest(
            course_title="Branded Course",
            course_slug="branded-course",
            modules=[{"title": "Intro", "lessons": [{"title": "One", "objective": "Learn one thing."}]}],
            branding={"product_name": "AcmeLearn"},
        ),
        str(tmp_path),
    )
    with ZipFile(result["package_path"]) as package:
        index = package.read("index.html").decode("utf-8")
    assert "Built with AcmeLearn." in index
    assert "Generated by Samrat Course MCP." not in index
